// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-_bCsRZiAcqSrgYG6VAfF5oSHL3lTwwg',
    appId: '1:145130646278:web:3aa2637239daf8c48c0c87',
    messagingSenderId: '145130646278',
    projectId: 'madlab-376d8',
    authDomain: 'madlab-376d8.firebaseapp.com',
    storageBucket: 'madlab-376d8.appspot.com',
    measurementId: 'G-058H8W5RTK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4mIq8PcZS7Jm6uWa2LT07qCy5uGTrl4w',
    appId: '1:145130646278:android:0b5eef67d90c6a0d8c0c87',
    messagingSenderId: '145130646278',
    projectId: 'madlab-376d8',
    storageBucket: 'madlab-376d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYE9Z85kb-5tSWouw5XQsJvg--WAMlQb4',
    appId: '1:145130646278:ios:cbbe1bc3a04f37ab8c0c87',
    messagingSenderId: '145130646278',
    projectId: 'madlab-376d8',
    storageBucket: 'madlab-376d8.appspot.com',
    iosClientId: '145130646278-2mh80jifs54488neiq1eqrmfgf0cm95o.apps.googleusercontent.com',
    iosBundleId: 'com.example.madlab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYE9Z85kb-5tSWouw5XQsJvg--WAMlQb4',
    appId: '1:145130646278:ios:cbbe1bc3a04f37ab8c0c87',
    messagingSenderId: '145130646278',
    projectId: 'madlab-376d8',
    storageBucket: 'madlab-376d8.appspot.com',
    iosClientId: '145130646278-2mh80jifs54488neiq1eqrmfgf0cm95o.apps.googleusercontent.com',
    iosBundleId: 'com.example.madlab',
  );
}
